---
name: Test Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'

      - name: Install Dependencies
        run: poetry install

      - name: Test Code Base
        run: poetry run pytest
